version: '3'
services:
  ui:
    build: ./src/ui    
    ports:
      - 3000:3000
    container_name: mvw_ui
    depends_on:
      - api
  api:
    build: ./src/api
    ports:
      - 5000:5000
    container_name: mvw_api